spring.application.name=OnlyDevAPI
#dataSource
spring.datasource.url=jdbc:mysql://localhost:3306/ONLYDEV
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=snsupratim004@mysql
#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Tomcat Server
server.port=8185